site_name: Giulia impara Mkdocs

theme:
  name: material
  language: it
  logo: assets/logo_rosso.svg
  site_url: https://giulia-genovese.github.io/imparandomkdocs/
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: amber
      accent: pink

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: deep purple
      accent: teal

  font:
    text: Helvetica
  
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.secttions
    - search.suggest
    - search.highlight
    - search.share

nav:
  - Bio: index.md
  - Tutorial: Tutorial.md
  - Sperimentazione: Sperimentazione.md
  - Game time: Game_time.md
  - Help: Help.md

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - glightbox
  - search
  - tags


extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/ops.giuly/
  consent:
    title: Cookies impossibili da rifiutare
    description: >- 
      Alfredo direbbe di non accettarli, però devi per forza
    cookies:
      analytics:
        name: Le tue abitudini
        checked: false
      latuavita:
        name: La tua vita
        checked: false
      aiuto:
        name: Aiuto
        checked: false
  generator: false

extra_css:
  - assets/styles.css

extra_javascript:
  - assets/scripts.js
