name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-glightbox

      - name: Check if mkdocs.yml exists
        run: |
          if [ -f mkdocs.yml ]; then
            echo "Found mkdocs.yml";
          else
            echo "No mkdocs.yml found. Please check your repository setup!";
            exit 1;
          fi

      - name: Build MkDocs site
        run: |
          echo "Running mkdocs build..."
          mkdocs build --verbose --clean  # Run build to create the site directory

      - name: Check if site folder exists after build
        run: |
          echo "Listing contents after mkdocs build"
          ls -l  # List the current directory contents to verify if ./site exists
          ls -l ./site || echo "No ./site directory found after build!"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./site

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: macos-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      - name: Debug downloaded artifact
        run: |
          echo "Listing downloaded artifact contents"
          ls -l ./site  # Ensure the downloaded artifact is extracted correctly

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2


    




